# Generated by Django 4.2.4 on 2023-08-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lecture_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='rating_count',
        ),
        migrations.DeleteModel(
            name='CourseRating',
        ),
    ]
