# Generated by Django 4.2.4 on 2023-08-15 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
        ('courses', '0004_remove_lecture_duration_remove_lecture_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='member_ship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.membership'),
            preserve_default=False,
        ),
    ]
