# Generated by Django 4.2.4 on 2023-08-15 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lecture_rate_lecture_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture_rate',
            name='count',
        ),
    ]
