# Generated by Django 4.2.4 on 2023-08-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_lecture_rate_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
