# Generated by Django 4.2.4 on 2023-08-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course/image'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='image',
            field=models.ImageField(upload_to='course/image'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.FileField(upload_to='course/video'),
        ),
    ]
