# Generated by Django 4.2.4 on 2023-08-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_image_alter_lecture_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='static/course/image'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='image',
            field=models.ImageField(upload_to='static/course/image'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.FileField(upload_to='static/course/video'),
        ),
    ]
